name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: quangduong2903
        password: dckr_pat_ZUKaEPwFyTeik1-VelSSGF1HYnA
    - name: Build and test
      run: docker build -t quangduong2903/material-mastery .
    - name: Push image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: quangduong2903/material-mastery

  run:

    needs: build-push

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Stop container and delete image
      run: docker stop material-mastery || true && docker rm -f material-mastery || true && docker rmi -f quangduong2903/material-mastery || true
    - name: Run container
      run: docker run -d -p 80:3000 --name material-mastery quangduong2903/material-mastery
